export const LISTING_LOADING = 'LISTING_LOADING';
export const LISTING_FAILED = 'LISTING_FAILED';
export const LISTING_RENDERED = 'LISTING_RENDERED';

export const ADD_LISTING = 'ADD_LISTING';

export const ADD_FAVORITE = 'ADD_FAVORITE';


